# Use the official Python image as the base image
FROM python:3.8

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project directory into the container
COPY . .

# Copy the quotes.json file into the container
COPY quotes.json .

# Expose the port that your Flask app will run on (replace 5000 with the appropriate port number)
EXPOSE 5000

# Set the environment variables (if needed)
# ENV ENV_VARIABLE_NAME value

# Run the Flask app
CMD ["python", "main.py"]
